### ISSUE TITLE
NameError: global name 'headerdict' is not defined

### ISSUE THREAD

**Issue by msz1621** [NotionalLabs/SQLiteZer#1]
When I try to run it as:

python SQLitezer.py -o test.txt -i accounts.db

it gives me this error:

NameError: global name 'headerdict' is not defined

I am using python 2.7.5 on windows 7

Thank you

**Comment by NotionalLabs** [comment]
Hey - you have the honor of being my first bug report, congratulations!

I'm not 100% sure what's causing this as I haven't been able to recreate it, but I think I identified the logical problem in the way the database parsing constructor handles errors. I submitted a fix for this a moment ago, so if you resync and let me know if that fixed it.

If you are pointing the script at the original database, I'd suggest you make a copy of it and point the script at the copy - the SQLite DB's are very dynamic while they are open and it can cause all sorts of issues.

Thanks,

Jim
